name: CI/CD
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Style
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Build
        run: docker build -t co0sh/hexagon-engine:latest .
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: co0sh/hexagon-engine:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: maddox/actions/ssh@master
        env:
          HOST: ${{ secrets.HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
        with:
          args: ~/the-world-anew/deploy-engine.sh
